In [25]:
import pandas as pd
import numpy as np
from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import matplotlib.pyplot as plt
import seaborn as sns

## MULTINOMIAL NAÏVE BAYES

### Bài tập 1

In [4]:
df_orders = pd.read_csv(r"D:\Workspace\HUS\Machine Learning\1. NaiveBayes\multinomial_nb_orders.csv")
display(df_orders.head())

,cuisine,city,device,user_segment,promo,fav_ingredient,spice_level,day_of_week,price_bucket
0,american,city_16,web,new,promo_1,onion,hot,Wed,high
1,thai,city_10,ios,family,promo_7,cilantro,mild,Wed,mid
2,american,city_18,ios,student,promo_1,cheese,hot,Fri,mid
3,japanese,city_10,web,family,promo_3,ginger,mild,Tue,high
4,vietnamese,city_10,web,family,none,fish_sauce,mild,Wed,low

In [5]:
df_orders = pd.get_dummies(df_orders)
display(df_orders.head())

,cuisine_american,cuisine_chinese,cuisine_indian,cuisine_italian,cuisine_japanese,cuisine_korean,cuisine_mediterranean,cuisine_mexican,cuisine_thai,cuisine_vietnamese,...,day_of_week_Mon,day_of_week_Sat,day_of_week_Sun,day_of_week_Thu,day_of_week_Tue,day_of_week_Wed,price_bucket_high,price_bucket_low,price_bucket_mid,price_bucket_very_high
0,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,True,True,False,False,False
1,False,False,False,False,False,False,False,False,True,False,...,False,False,False,False,False,True,False,False,True,False
2,True,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,True,False,False,False,False,False,...,False,False,False,False,True,False,True,False,False,False
4,False,False,False,False,False,False,False,False,False,True,...,False,False,False,False,False,True,False,True,False,False

In [18]:
print(df_orders.columns)

Index(['cuisine_american', 'cuisine_chinese', 'cuisine_indian',
       'cuisine_italian', 'cuisine_japanese', 'cuisine_korean',
       'cuisine_mediterranean', 'cuisine_mexican', 'cuisine_thai',
       'cuisine_vietnamese', 'city_city_1', 'city_city_10', 'city_city_11',
       'city_city_12', 'city_city_13', 'city_city_14', 'city_city_15',
       'city_city_16', 'city_city_17', 'city_city_18', 'city_city_19',
       'city_city_2', 'city_city_20', 'city_city_3', 'city_city_4',
       'city_city_5', 'city_city_6', 'city_city_7', 'city_city_8',
       'city_city_9', 'device_android', 'device_desktop_app', 'device_ios',
       'device_tablet', 'device_web', 'user_segment_budget',
       'user_segment_family', 'user_segment_new', 'user_segment_returning',
       'user_segment_student', 'user_segment_vip', 'promo_none',
       'promo_promo_1', 'promo_promo_2', 'promo_promo_3', 'promo_promo_4',
       'promo_promo_5', 'promo_promo_6', 'promo_promo_7', 'promo_promo_8',
       'fav_ingredient_basil', 'fav_ingredient_cheese', 'fav_ingredient_chili',
       'fav_ingredient_cilantro', 'fav_ingredient_cumin',
       'fav_ingredient_fish_sauce', 'fav_ingredient_garlic',
       'fav_ingredient_ginger', 'fav_ingredient_lemon', 'fav_ingredient_mint',
       'fav_ingredient_miso', 'fav_ingredient_onion', 'fav_ingredient_oregano',
       'fav_ingredient_sesame', 'fav_ingredient_soy', 'fav_ingredient_tomato',
       'fav_ingredient_turmeric', 'fav_ingredient_yogurt',
       'spice_level_extra_hot', 'spice_level_hot', 'spice_level_medium',
       'spice_level_mild', 'spice_level_none', 'day_of_week_Fri',
       'day_of_week_Mon', 'day_of_week_Sat', 'day_of_week_Sun',
       'day_of_week_Thu', 'day_of_week_Tue', 'day_of_week_Wed',
       'price_bucket_high', 'price_bucket_low', 'price_bucket_mid',
       'price_bucket_very_high'],
      dtype='object')

In [7]:
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report

# Select the target variable (y) and features (X)
X = df_orders.drop(columns=[col for col in df_orders.columns if col.startswith('cuisine_')])
y = df_orders[[col for col in df_orders.columns if col.startswith('cuisine_')]]

# Convert the one-hot encoded 'y' back to a single column of labels
y = y.idxmax(axis=1)

# Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

print("Training features shape (X_train):", X_train.shape)
print("Testing features shape (X_test):", X_test.shape)
print("Training labels shape (y_train):", y_train.shape)
print("Testing labels shape (y_test):", y_test.shape)

# Train the Multinomial Naive Bayes model
model = MultinomialNB()
model.fit(X_train, y_train)

# Make predictions on the test set
y_pred = model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
report = classification_report(y_test, y_pred)

print("\nModel Evaluation:")
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:\n", report)

Training features shape (X_train): (2100, 74)
Testing features shape (X_test): (900, 74)
Training labels shape (y_train): (2100,)
Testing labels shape (y_test): (900,)

Model Evaluation:
Accuracy: 0.4844

Classification Report:
                        precision    recall  f1-score   support

     cuisine_american       0.60      0.66      0.63       125
      cuisine_chinese       0.40      0.55      0.46       113
       cuisine_indian       0.94      0.91      0.93        91
      cuisine_italian       0.47      0.40      0.44        92
     cuisine_japanese       0.33      0.30      0.31        88
       cuisine_korean       0.13      0.04      0.06        51
cuisine_mediterranean       0.33      0.32      0.32        69
      cuisine_mexican       0.67      0.49      0.57        89
         cuisine_thai       0.37      0.41      0.39        96
   cuisine_vietnamese       0.36      0.44      0.39        86

             accuracy                           0.48       900
            macro avg       0.46      0.45      0.45       900
         weighted avg       0.48      0.48      0.48       900

## BERNOULLI NAÏVE BAYES

### Bài tập 2

In [21]:
# 1. Đọc dữ liệu
print("Đọc dữ liệu từ các file CSV...")

# Đọc dữ liệu training
train_values = pd.read_csv('train_values.csv')
train_labels = pd.read_csv('train_labels.csv')

# Đọc dữ liệu test
test_values = pd.read_csv('test_values.csv')

Đọc dữ liệu từ các file CSV...

#### Bài 1

##### a. Hardcode

In [22]:
# Merge training data with labels
train_data = train_values.merge(train_labels, on='building_id')

# Select only the required categorical features
categorical_features = [
    'land_surface_condition',
    'foundation_type', 
    'roof_type',
    'ground_floor_type',
    'other_floor_type',
    'position',
    'plan_configuration',
    'legal_ownership_status'
]

# Extract features and target
X_train = train_data[categorical_features]
y_train = train_data['damage_grade']
X_test = test_values[categorical_features]

print("Training data shape:", X_train.shape)
print("Test data shape:", X_test.shape)
print("Target variable distribution:")
print(y_train.value_counts().sort_index())

Training data shape: (260601, 8)
Test data shape: (86868, 8)
Target variable distribution:
damage_grade
1     25124
2    148259
3     87218
Name: count, dtype: int64

In [30]:
def custom_multinomial_nb(X_train, y_train, X_test, alpha=1.0):
    """
    Custom implementation of Multinomial Naive Bayes
    """
    # Get unique classes and features
    classes = np.unique(y_train)
    features = X_train.columns
    
    # Calculate class probabilities P(y)
    class_probs = {}
    for cls in classes:
        class_probs[cls] = np.sum(y_train == cls) / len(y_train)
    
    # Calculate feature probabilities P(x_i|y) for each class
    feature_probs = {}
    
    for cls in classes:
        feature_probs[cls] = {}
        class_data = X_train[y_train == cls]
        
        for feature in features:
            feature_probs[cls][feature] = {}
            feature_values = np.unique(X_train[feature])
            
            for value in feature_values:
                # Count occurrences of this feature value in this class
                count = np.sum(class_data[feature] == value)
                # Total number of samples in this class
                total_class_samples = len(class_data)
                # Number of possible feature values
                num_feature_values = len(feature_values)
                
                # Apply Laplace smoothing
                prob = (count + alpha) / (total_class_samples + alpha * num_feature_values)
                feature_probs[cls][feature][value] = prob
    
    # Make predictions
    predictions = []
    
    for i in range(len(X_test)):
        class_scores = {}
        
        for cls in classes:
            # Start with log of class probability
            score = np.log(class_probs[cls])
            
            # Add log probabilities of each feature
            for feature in features:
                feature_value = X_test.iloc[i][feature]
                if feature_value in feature_probs[cls][feature]:
                    score += np.log(feature_probs[cls][feature][feature_value])
                else:
                    # Handle unseen feature values with smoothing
                    feature_values = list(feature_probs[cls][feature].keys())
                    num_feature_values = len(feature_values)
                    class_data = X_train[y_train == cls]
                    total_class_samples = len(class_data)
                    prob = alpha / (total_class_samples + alpha * (num_feature_values + 1))
                    score += np.log(prob)
            
            class_scores[cls] = score
        
        # Predict class with highest score
        predicted_class = max(class_scores.keys(), key=lambda x: class_scores[x])
        predictions.append(predicted_class)
    
    return np.array(predictions)

# Train and predict with custom implementation
print("Training Custom Multinomial Naive Bayes...")
custom_predictions = custom_multinomial_nb(X_train, y_train, X_test)

print(f"Custom implementation completed. Predictions shape: {custom_predictions.shape}")
print(f"Prediction distribution:")
unique_preds, counts = np.unique(custom_predictions, return_counts=True)
for pred, count in zip(unique_preds, counts):
    print(f"Class {pred}: {count} predictions")

Training Custom Multinomial Naive Bayes...
Custom implementation completed. Predictions shape: (86868,)
Prediction distribution:
Class 1: 7611 predictions
Class 2: 73749 predictions
Class 3: 5508 predictions

##### b. SKlearn

In [26]:
# Sklearn Implementation for comparison

# Encode categorical variables for sklearn
le_dict = {}
X_train_encoded = X_train.copy()
X_test_encoded = X_test.copy()

for feature in categorical_features:
    le = LabelEncoder()
    # Fit on combined data to handle all possible values
    combined_values = pd.concat([X_train[feature], X_test[feature]], axis=0)
    le.fit(combined_values)
    
    X_train_encoded[feature] = le.transform(X_train[feature])
    X_test_encoded[feature] = le.transform(X_test[feature])
    le_dict[feature] = le

print("Training Sklearn Multinomial Naive Bayes...")

# Train sklearn model
sklearn_model = MultinomialNB(alpha=1.0)
sklearn_model.fit(X_train_encoded, y_train)

# Make predictions
sklearn_predictions = sklearn_model.predict(X_test_encoded)

print(f"Sklearn implementation completed. Predictions shape: {sklearn_predictions.shape}")
print(f"Sklearn prediction distribution:")
unique_preds, counts = np.unique(sklearn_predictions, return_counts=True)
for pred, count in zip(unique_preds, counts):
    print(f"Class {pred}: {count} predictions")

Training Sklearn Multinomial Naive Bayes...
Sklearn implementation completed. Predictions shape: (86868,)
Sklearn prediction distribution:
Class 1: 6732 predictions
Class 2: 80136 predictions

##### Tổng kết và phân tích kết quả

In [27]:
# Compare predictions between custom and sklearn implementations

print("Comparison between Custom and Sklearn implementations:")
print("="*60)

# Check if predictions are the same
same_predictions = np.sum(custom_predictions == sklearn_predictions)
total_predictions = len(custom_predictions)
agreement_rate = same_predictions / total_predictions

print(f"Total test samples: {total_predictions}")
print(f"Predictions that match: {same_predictions}")
print(f"Agreement rate: {agreement_rate:.4f} ({agreement_rate*100:.2f}%)")

# Show first 20 predictions for comparison
print("\nFirst 20 predictions comparison:")
print("Index | Custom | Sklearn")
print("-" * 25)
for i in range(min(20, len(custom_predictions))):
    match_indicator = "✓" if custom_predictions[i] == sklearn_predictions[i] else "✗"
    print(f"{i:5d} | {custom_predictions[i]:6d} | {sklearn_predictions[i]:7d} {match_indicator}")

# Show distribution comparison
print("\nPrediction distribution comparison:")
print("Class | Custom | Sklearn")
print("-" * 23)
for cls in sorted(np.unique(np.concatenate([custom_predictions, sklearn_predictions]))):
    custom_count = np.sum(custom_predictions == cls)
    sklearn_count = np.sum(sklearn_predictions == cls)
    print(f"{cls:5d} | {custom_count:6d} | {sklearn_count:7d}")

Comparison between Custom and Sklearn implementations:
============================================================
Total test samples: 86868
Predictions that match: 76573
Agreement rate: 0.8815 (88.15%)

First 20 predictions comparison:
Index | Custom | Sklearn
-------------------------
    0 |      2 |       2 ✓
    1 |      2 |       2 ✓
    2 |      2 |       2 ✓
    3 |      1 |       1 ✓
    4 |      3 |       2 ✗
    5 |      2 |       2 ✓
    6 |      2 |       2 ✓
    7 |      2 |       2 ✓
    8 |      2 |       2 ✓
    9 |      2 |       2 ✓
   10 |      2 |       2 ✓
   11 |      2 |       2 ✓
   12 |      2 |       2 ✓
   13 |      2 |       2 ✓
   14 |      1 |       1 ✓
   15 |      2 |       2 ✓
   16 |      2 |       2 ✓
   17 |      2 |       2 ✓
   18 |      2 |       2 ✓
   19 |      2 |       2 ✓

Prediction distribution comparison:
Class | Custom | Sklearn
-----------------------
    1 |   7611 |    6732
    2 |  73749 |   80136
    3 |   5508 |       0

In [28]:
# Validation using a subset of training data to compare accuracy

# Split training data for validation
from sklearn.model_selection import train_test_split

X_train_val, X_test_val, y_train_val, y_test_val = train_test_split(
    X_train, y_train, test_size=0.2, random_state=42, stratify=y_train
)

print("Validation on training data subset:")
print("="*50)

# Custom implementation validation
custom_val_predictions = custom_multinomial_nb(X_train_val, y_train_val, X_test_val)
custom_accuracy = accuracy_score(y_test_val, custom_val_predictions)

print(f"Custom Implementation Accuracy: {custom_accuracy:.4f}")
print("\nCustom Implementation Classification Report:")
print(classification_report(y_test_val, custom_val_predictions))

# Sklearn implementation validation
X_train_val_encoded = X_train_val.copy()
X_test_val_encoded = X_test_val.copy()

for feature in categorical_features:
    le = LabelEncoder()
    combined_values = pd.concat([X_train_val[feature], X_test_val[feature]], axis=0)
    le.fit(combined_values)
    
    X_train_val_encoded[feature] = le.transform(X_train_val[feature])
    X_test_val_encoded[feature] = le.transform(X_test_val[feature])

sklearn_val_model = MultinomialNB(alpha=1.0)
sklearn_val_model.fit(X_train_val_encoded, y_train_val)
sklearn_val_predictions = sklearn_val_model.predict(X_test_val_encoded)
sklearn_accuracy = accuracy_score(y_test_val, sklearn_val_predictions)

print(f"\nSklearn Implementation Accuracy: {sklearn_accuracy:.4f}")
print("\nSklearn Implementation Classification Report:")
print(classification_report(y_test_val, sklearn_val_predictions))

print(f"\nAccuracy difference: {abs(custom_accuracy - sklearn_accuracy):.4f}")

Validation on training data subset:
==================================================
Custom Implementation Accuracy: 0.5681

Custom Implementation Classification Report:
              precision    recall  f1-score   support

           1       0.47      0.42      0.44      5025
           2       0.58      0.87      0.70     29652
           3       0.50      0.10      0.16     17444

    accuracy                           0.57     52121
   macro avg       0.52      0.46      0.43     52121
weighted avg       0.54      0.57      0.49     52121


Sklearn Implementation Accuracy: 0.5602

Sklearn Implementation Classification Report:
              precision    recall  f1-score   support

           1       0.38      0.30      0.34      5025
           2       0.58      0.93      0.71     29652
           3       0.00      0.00      0.00     17444

    accuracy                           0.56     52121
   macro avg       0.32      0.41      0.35     52121
weighted avg       0.36      0.56      0.44     52121


Accuracy difference: 0.0079

C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])
C:\Users\ADMIN\AppData\Roaming\Python\Python313\site-packages\sklearn\metrics\_classification.py:1731: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", result.shape[0])

#### Bài 2

##### a. Hardcode

In [ ]:
print(f"Training data shape: {train_values.shape}")
print(f"Training labels shape: {train_labels.shape}")
print(f"Test data shape: {test_values.shape}")

# Hiển thị thông tin cơ bản về dữ liệu
print("\nCột đầu tiên của train_values:")
print(train_values.head())

print("\nCột đầu tiên của train_labels:")
print(train_labels.head())

print("\nPhân phối damage_grade:")
print(train_labels['damage_grade'].value_counts().sort_index())

Đọc dữ liệu từ các file CSV...
Training data shape: (260601, 39)
Training labels shape: (260601, 2)
Test data shape: (86868, 39)

Cột đầu tiên của train_values:
   building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0       802906               6             487           12198
1        28830               8             900            2812
2        94947              21             363            8973
3       590882              22             418           10694
4       201944              11             131            1488

   count_floors_pre_eq  age  area_percentage  height_percentage  \
0                    2   30                6                  5
1                    2   10                8                  7
2                    2   10                5                  5
3                    2   10                6                  5
4                    3   30                8                  9

  land_surface_condition foundation_type  ... has_secondary_use_agriculture  \
0                      t               r  ...                             0
1                      o               r  ...                             0
2                      t               r  ...                             0
3                      t               r  ...                             0
4                      t               r  ...                             0

  has_secondary_use_hotel has_secondary_use_rental  \
0                       0                        0
1                       0                        0
2                       0                        0
3                       0                        0
4                       0                        0

  has_secondary_use_institution has_secondary_use_school  \
0                             0                        0
1                             0                        0
2                             0                        0
3                             0                        0
4                             0                        0

   has_secondary_use_industry  has_secondary_use_health_post  \
0                           0                              0
1                           0                              0
2                           0                              0
3                           0                              0
4                           0                              0

   has_secondary_use_gov_office  has_secondary_use_use_police  \
0                             0                             0
1                             0                             0
2                             0                             0
3                             0                             0
4                             0                             0

   has_secondary_use_other
0                        0
1                        0
2                        0
3                        0
4                        0

[5 rows x 39 columns]

Cột đầu tiên của train_labels:
   building_id  damage_grade
0       802906             3
1        28830             2
2        94947             3
3       590882             2
4       201944             3

Phân phối damage_grade:
damage_grade
1     25124
2    148259
3     87218
Name: count, dtype: int64
Training data shape: (260601, 39)
Training labels shape: (260601, 2)
Test data shape: (86868, 39)

Cột đầu tiên của train_values:
   building_id  geo_level_1_id  geo_level_2_id  geo_level_3_id  \
0       802906               6             487           12198
1        28830               8             900            2812
2        94947              21             363            8973
3       590882              22             418           10694
4       201944              11             131            1488

   count_floors_pre_eq  age  area_percentage  height_percentage  \
0                    2   30                6                  5
1                    2   10                8                  7
2                    2   10                5                  5
3                    2   10                6                  5
4                    3   30                8                  9

  land_surface_condition foundation_type  ... has_secondary_use_agriculture  \
0                      t               r  ...                             0
1                      o               r  ...                             0
2                      t               r  ...                             0
3                      t               r  ...                             0
4                      t               r  ...                             0

  has_secondary_use_hotel has_secondary_use_rental  \
0                       0                        0
1                       0                        0
2                       0                        0
3                       0                        0
4                       0                        0

  has_secondary_use_institution has_secondary_use_school  \
0                             0                        0
1                             0                        0
2                             0                        0
3                             0                        0
4                             0                        0

   has_secondary_use_industry  has_secondary_use_health_post  \
0                           0                              0
1                           0                              0
2                           0                              0
3                           0                              0
4                           0                              0

   has_secondary_use_gov_office  has_secondary_use_use_police  \
0                             0                             0
1                             0                             0
2                             0                             0
3                             0                             0
4                             0                             0

   has_secondary_use_other
0                        0
1                        0
2                        0
3                        0
4                        0

[5 rows x 39 columns]

Cột đầu tiên của train_labels:
   building_id  damage_grade
0       802906             3
1        28830             2
2        94947             3
3       590882             2
4       201944             3

Phân phối damage_grade:
damage_grade
1     25124
2    148259
3     87218
Name: count, dtype: int64

In [9]:
# 2. Trích xuất các trường nhị phân theo yêu cầu
print("Trích xuất 22 trường dữ liệu nhị phân...")

# Danh sách 22 trường nhị phân theo yêu cầu
binary_features = [
    # Superstructure features (i-xi)
    'has_superstructure_adobe_mud',           # i
    'has_superstructure_mud_mortar_stone',    # ii  
    'has_superstructure_stone_flag',          # iii
    'has_superstructure_cement_mortar_stone', # iv
    'has_superstructure_mud_mortar_brick',    # v
    'has_superstructure_cement_mortar_brick', # vi
    'has_superstructure_timber',              # vii
    'has_superstructure_bamboo',              # viii
    'has_superstructure_rc_non_engineered',   # ix
    'has_superstructure_rc_engineered',       # x
    'has_superstructure_other',               # xi
    
    # Secondary use features (xii-xxii)
    'has_secondary_use',                      # xii
    'has_secondary_use_agriculture',          # xiii
    'has_secondary_use_hotel',                # xiv
    'has_secondary_use_rental',               # xv
    'has_secondary_use_institution',          # xvi
    'has_secondary_use_school',               # xvii
    'has_secondary_use_industry',             # xviii
    'has_secondary_use_health_post',          # xix
    'has_secondary_use_gov_office',           # xx
    'has_secondary_use_use_police',           # xxi
    'has_secondary_use_other'                 # xxii
]

print(f"Số lượng trường nhị phân: {len(binary_features)}")

# Kiểm tra xem tất cả các trường có tồn tại trong dữ liệu không
missing_features = [feat for feat in binary_features if feat not in train_values.columns]
if missing_features:
    print(f"Các trường bị thiếu: {missing_features}")
else:
    print("Tất cả các trường đều tồn tại trong dữ liệu!")

# Trích xuất dữ liệu training
X_train = train_values[binary_features].copy()
y_train = train_labels['damage_grade'].copy()

# Trích xuất dữ liệu test
X_test = test_values[binary_features].copy()

print(f"\nShape của X_train: {X_train.shape}")
print(f"Shape của y_train: {y_train.shape}")
print(f"Shape của X_test: {X_test.shape}")

# Kiểm tra dữ liệu
print(f"\nKiểm tra giá trị unique trong các trường nhị phân:")
for feature in binary_features[:5]:  # Hiển thị 5 cột đầu
    unique_vals = X_train[feature].unique()
    print(f"{feature}: {unique_vals}")
    
print("\nMẫu dữ liệu X_train:")
print(X_train.head())

Trích xuất 22 trường dữ liệu nhị phân...
Số lượng trường nhị phân: 22
Tất cả các trường đều tồn tại trong dữ liệu!

Shape của X_train: (260601, 22)
Shape của y_train: (260601,)
Shape của X_test: (86868, 22)

Kiểm tra giá trị unique trong các trường nhị phân:
has_superstructure_adobe_mud: [1 0]
has_superstructure_mud_mortar_stone: [1 0]
has_superstructure_stone_flag: [0 1]
has_superstructure_cement_mortar_stone: [0 1]
has_superstructure_mud_mortar_brick: [0 1]

Mẫu dữ liệu X_train:
   has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  \
0                             1                                    1
1                             0                                    1
2                             0                                    1
3                             0                                    1
4                             1                                    0

   has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  \
0                              0                                       0
1                              0                                       0
2                              0                                       0
3                              0                                       0
4                              0                                       0

   has_superstructure_mud_mortar_brick  \
0                                    0
1                                    0
2                                    0
3                                    0
4                                    0

   has_superstructure_cement_mortar_brick  has_superstructure_timber  \
0                                       0                          0
1                                       0                          0
2                                       0                          0
3                                       0                          1
4                                       0                          0

   has_superstructure_bamboo  has_superstructure_rc_non_engineered  \
0                          0                                     0
1                          0                                     0
2                          0                                     0
3                          1                                     0
4                          0                                     0

   has_superstructure_rc_engineered  ...  has_secondary_use_agriculture  \
0                                 0  ...                              0
1                                 0  ...                              0
2                                 0  ...                              0
3                                 0  ...                              0
4                                 0  ...                              0

   has_secondary_use_hotel  has_secondary_use_rental  \
0                        0                         0
1                        0                         0
2                        0                         0
3                        0                         0
4                        0                         0

   has_secondary_use_institution  has_secondary_use_school  \
0                              0                         0
1                              0                         0
2                              0                         0
3                              0                         0
4                              0                         0

   has_secondary_use_industry  has_secondary_use_health_post  \
0                           0                              0
1                           0                              0
2                           0                              0
3                           0                              0
4                           0                              0

   has_secondary_use_gov_office  has_secondary_use_use_police  \
0                             0                             0
1                             0                             0
2                             0                             0
3                             0                             0
4                             0                             0

   has_secondary_use_other
0                        0
1                        0
2                        0
3                        0
4                        0

[5 rows x 22 columns]

In [10]:
target_feature = 'damage_grade'

# Bước 1: Tính các xác suất p_k := N_k / N cho mỗi class
print("Bước 1: Tính xác suất prior cho mỗi class...")

Y = y_train  # damage_grade từ training data
labels = np.zeros((len(set(Y)), 2), dtype=object) 

# Liệt kê các nhãn (label) khác nhau và tính xác suất P_k của mỗi nhãn
id = 0
for label in sorted(set(Y)):  # sắp xếp để đảm bảo thứ tự 1, 2, 3
    labels[id, 0] = label
    labels[id, 1] = (Y == label).sum() / len(Y)
    print(f"Class {label}: {(Y == label).sum()} samples, probability = {labels[id, 1]:.4f}")
    id += 1

print(f"\nLabels array shape: {labels.shape}")
print("Labels array:")
print(labels)

Bước 1: Tính xác suất prior cho mỗi class...
Class 1: 25124 samples, probability = 0.0964
Class 2: 148259 samples, probability = 0.5689
Class 3: 87218 samples, probability = 0.3347

Labels array shape: (3, 2)
Labels array:
[[1 np.float64(0.09640791861888481)]
 [2 np.float64(0.5689118614280068)]
 [3 np.float64(0.33468021995310837)]]

In [11]:
# Bước 2: Định nghĩa hàm tính P_ik - xác suất feature i = 1 trong class k
def Pik_feature_per_class(X):
    """
    Tính xác suất feature nhận giá trị 1 trong một class
    Returns the prob. of feature per class
    """
    X = np.array(X)
    # count the number of element x_m which has field i^th : x_im = 1
    count = (X == 1).sum()
    # P_ik := [|{xm in class k : x_im = 1}|] / N_k 
    return count / len(X) if len(X) > 0 else 0

print("Hàm Pik_feature_per_class đã được định nghĩa!")

Hàm Pik_feature_per_class đã được định nghĩa!

In [ ]:
# Bước 3: Định nghĩa hàm dự đoán
def predict_output_label(X, x_input, p_labels, target_feature):
    """
    Dự đoán nhãn cho một mẫu dữ liệu đầu vào
    
    Parameters:
    X: DataFrame chứa dữ liệu training
    x_input: Series chứa dữ liệu cần dự đoán (chỉ các features, không có target)
    p_labels: array chứa các class và xác suất prior
    target_feature: tên của cột target
    """
    # Score for each class (bắt đầu với log prior)
    p = np.log(np.array(p_labels[:, 1], dtype=float))

    for k in range(len(p)):
        # Lấy tất cả mẫu thuộc class k
        Xk = X[X[target_feature] == p_labels[k, 0]]
        
        # Tính likelihood cho từng feature
        for i in range(len(x_input)):
            # Tính P_ik: xác suất feature i = 1 trong class k
            Pik = Pik_feature_per_class(Xk.iloc[:, i])  # Chú ý: i tương ứng với cột trong X_train
            
            if Pik != 0 and Pik != 1:  # Tránh log(0)
                # Bernoulli likelihood: P(x_i | class_k)
                # Nếu x_i = 1: P_ik, nếu x_i = 0: (1 - P_ik)
                likelihood = x_input.iloc[i] * Pik + (1 - x_input.iloc[i]) * (1 - Pik)
                p[k] += np.log(likelihood)
            elif Pik == 0:  # Tất cả mẫu trong class k có feature i = 0
                if x_input.iloc[i] == 1:
                    p[k] += np.log(1e-10)  # Xác suất rất nhỏ thay vì 0
                # Nếu x_input.iloc[i] == 0 thì likelihood = 1, log(1) = 0
            elif Pik == 1:  # Tất cả mẫu trong class k có feature i = 1
                if x_input.iloc[i] == 0:
                    p[k] += np.log(1e-10)  # Xác suất rất nhỏ thay vì 0
                # Nếu x_input.iloc[i] == 1 thì likelihood = 1, log(1) = 0

    # Chọn class có score cao nhất
    y_star = np.argmax(p)
    return p_labels[y_star, 0]

print("Hàm predict_output_label đã được định nghĩa!")

Hàm predict_output_label đã được định nghĩa!

In [ ]:
print("Bước 4: Chuẩn bị dữ liệu training...")

# Tạo DataFrame training bao gồm cả features và target
X_Train_combined = X_train.copy()
X_Train_combined[target_feature] = y_train

print(f"X_Train_combined shape: {X_Train_combined.shape}")
print(f"Columns: {list(X_Train_combined.columns)}")
print(f"Target feature: {target_feature}")

# Kiểm tra mẫu dữ liệu
print("\nMẫu dữ liệu X_Train_combined:")
print(X_Train_combined.head())

Bước 4: Chuẩn bị dữ liệu training...
X_Train_combined shape: (260601, 23)
Columns: ['has_superstructure_adobe_mud', 'has_superstructure_mud_mortar_stone', 'has_superstructure_stone_flag', 'has_superstructure_cement_mortar_stone', 'has_superstructure_mud_mortar_brick', 'has_superstructure_cement_mortar_brick', 'has_superstructure_timber', 'has_superstructure_bamboo', 'has_superstructure_rc_non_engineered', 'has_superstructure_rc_engineered', 'has_superstructure_other', 'has_secondary_use', 'has_secondary_use_agriculture', 'has_secondary_use_hotel', 'has_secondary_use_rental', 'has_secondary_use_institution', 'has_secondary_use_school', 'has_secondary_use_industry', 'has_secondary_use_health_post', 'has_secondary_use_gov_office', 'has_secondary_use_use_police', 'has_secondary_use_other', 'damage_grade']
Target feature: damage_grade

Mẫu dữ liệu X_Train_combined:
   has_superstructure_adobe_mud  has_superstructure_mud_mortar_stone  \
0                             1                                    1
1                             0                                    1
2                             0                                    1
3                             0                                    1
4                             1                                    0

   has_superstructure_stone_flag  has_superstructure_cement_mortar_stone  \
0                              0                                       0
1                              0                                       0
2                              0                                       0
3                              0                                       0
4                              0                                       0

   has_superstructure_mud_mortar_brick  \
0                                    0
1                                    0
2                                    0
3                                    0
4                                    0

   has_superstructure_cement_mortar_brick  has_superstructure_timber  \
0                                       0                          0
1                                       0                          0
2                                       0                          0
3                                       0                          1
4                                       0                          0

   has_superstructure_bamboo  has_superstructure_rc_non_engineered  \
0                          0                                     0
1                          0                                     0
2                          0                                     0
3                          1                                     0
4                          0                                     0

   has_superstructure_rc_engineered  ...  has_secondary_use_hotel  \
0                                 0  ...                        0
1                                 0  ...                        0
2                                 0  ...                        0
3                                 0  ...                        0
4                                 0  ...                        0

   has_secondary_use_rental  has_secondary_use_institution  \
0                         0                              0
1                         0                              0
2                         0                              0
3                         0                              0
4                         0                              0

   has_secondary_use_school  has_secondary_use_industry  \
0                         0                           0
1                         0                           0
2                         0                           0
3                         0                           0
4                         0                           0

   has_secondary_use_health_post  has_secondary_use_gov_office  \
0                              0                             0
1                              0                             0
2                              0                             0
3                              0                             0
4                              0                             0

   has_secondary_use_use_police  has_secondary_use_other  damage_grade
0                             0                        0             3
1                             0                        0             2
2                             0                        0             3
3                             0                        0             2
4                             0                        0             3

[5 rows x 23 columns]

In [14]:
# Bước 5: Thực hiện dự đoán trên tập test (test với subset nhỏ trước)
print("Bước 5: Dự đoán trên tập test...")

# Test với 100 mẫu đầu tiên để kiểm tra
test_size = 100
print(f"Testing với {test_size} mẫu đầu tiên...")

X_test_small = X_test.iloc[:test_size].copy()
Y_pred_small = np.zeros(test_size, dtype=y_train.dtype)

# Dự đoán cho từng mẫu trong test set nhỏ
print("Đang dự đoán...")
for i in range(test_size):
    if i % 25 == 0:  # In tiến trình mỗi 25 mẫu
        print(f"Đã xử lý {i}/{test_size} mẫu...")
    
    # Dự đoán cho mẫu thứ i
    Y_pred_small[i] = predict_output_label(X_Train_combined, X_test_small.iloc[i, :], labels, target_feature)

print(f"Hoàn thành dự đoán cho {test_size} mẫu!")
print(f"Kết quả dự đoán: {Y_pred_small}")

# Phân phối kết quả dự đoán
unique, counts = np.unique(Y_pred_small, return_counts=True)
print(f"\nPhân phối dự đoán (trên {test_size} mẫu):")
for class_val, count in zip(unique, counts):
    print(f"Class {class_val}: {count} mẫu ({count/test_size*100:.2f}%)")

# Test thử với 1 mẫu cụ thể để kiểm tra chi tiết
print(f"\nTest với mẫu đầu tiên:")
print(f"Input features: {X_test_small.iloc[0].values}")
print(f"Predicted class: {Y_pred_small[0]}")

Bước 5: Dự đoán trên tập test...
Testing với 100 mẫu đầu tiên...
Đang dự đoán...
Đã xử lý 0/100 mẫu...

Đã xử lý 25/100 mẫu...
Đã xử lý 50/100 mẫu...
Đã xử lý 50/100 mẫu...
Đã xử lý 75/100 mẫu...
Đã xử lý 75/100 mẫu...
Hoàn thành dự đoán cho 100 mẫu!
Kết quả dự đoán: [2 2 2 1 2 2 1 2 2 2 2 2 2 2 1 2 2 2 3 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 1 2 2
 3 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 1 1 2 2 2 2 2 2 2 2]

Phân phối dự đoán (trên 100 mẫu):
Class 1: 9 mẫu (9.00%)
Class 2: 88 mẫu (88.00%)
Class 3: 3 mẫu (3.00%)

Test với mẫu đầu tiên:
Input features: [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Predicted class: 2
Hoàn thành dự đoán cho 100 mẫu!
Kết quả dự đoán: [2 2 2 1 2 2 1 2 2 2 2 2 2 2 1 2 2 2 3 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 1 2 2
 3 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 1 1 2 2 2 2 2 2 2 2]

Phân phối dự đoán (trên 100 mẫu):
Class 1: 9 mẫu (9.00%)
Class 2: 88 mẫu (88.00%)
Class 3: 3 mẫu (3.00%)

Test với mẫu đầu tiên:
Input features: [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
Predicted class: 2

##### b. Sklearn

In [15]:
# Sử dụng sklearn BernoulliNB
print("Sử dụng sklearn BernoulliNB...")

# Khởi tạo và huấn luyện model
sklearn_bnb = BernoulliNB()
sklearn_bnb.fit(X_train, y_train)

# Dự đoán trên cùng 100 mẫu để so sánh
sklearn_pred_small = sklearn_bnb.predict(X_test_small)

print("Sklearn BernoulliNB - Kết quả dự đoán (100 mẫu đầu):")
print(sklearn_pred_small)

# Phân phối kết quả sklearn
unique_sklearn, counts_sklearn = np.unique(sklearn_pred_small, return_counts=True)
print(f"\nPhân phối dự đoán sklearn (trên {test_size} mẫu):")
for class_val, count in zip(unique_sklearn, counts_sklearn):
    print(f"Class {class_val}: {count} mẫu ({count/test_size*100:.2f}%)")

# So sánh kết quả
print(f"\nSo sánh trên {test_size} mẫu đầu:")
print("Custom vs Sklearn:")
match_count = np.sum(Y_pred_small == sklearn_pred_small)
print(f"Số mẫu dự đoán giống nhau: {match_count}/{test_size} ({match_count/test_size*100:.2f}%)")

# So sánh chi tiết cho 10 mẫu đầu
print("\nSo sánh chi tiết 10 mẫu đầu:")
print("Mẫu | Custom | Sklearn")
print("----|--------|--------")
for i in range(10):
    print(f" {i:2d}  |   {Y_pred_small[i]}    |    {sklearn_pred_small[i]}")

print(f"\nDự đoán cho mẫu đầu tiên:")
print(f"Custom: {Y_pred_small[0]}")
print(f"Sklearn: {sklearn_pred_small[0]}")

Sử dụng sklearn BernoulliNB...
Sklearn BernoulliNB - Kết quả dự đoán (100 mẫu đầu):
[2 2 2 1 2 2 1 2 2 2 2 2 2 2 1 2 2 2 3 2 2 2 2 2 2 2 3 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 2 2 1 2 2
 3 2 2 2 2 2 2 2 1 2 2 2 1 2 2 2 1 1 2 2 2 2 2 2 2 2]

Phân phối dự đoán sklearn (trên 100 mẫu):
Class 1: 9 mẫu (9.00%)
Class 2: 88 mẫu (88.00%)
Class 3: 3 mẫu (3.00%)

So sánh trên 100 mẫu đầu:
Custom vs Sklearn:
Số mẫu dự đoán giống nhau: 100/100 (100.00%)

So sánh chi tiết 10 mẫu đầu:
Mẫu | Custom | Sklearn
----|--------|--------
  0  |   2    |    2
  1  |   2    |    2
  2  |   2    |    2
  3  |   1    |    1
  4  |   2    |    2
  5  |   2    |    2
  6  |   1    |    1
  7  |   2    |    2
  8  |   2    |    2
  9  |   2    |    2

Dự đoán cho mẫu đầu tiên:
Custom: 2
Sklearn: 2

In [16]:
# Dự đoán toàn bộ test set để tạo submission file
print("Dự đoán toàn bộ test set...")

# Sklearn prediction cho toàn bộ test set (nhanh hơn)
Y_pred_full_sklearn = sklearn_bnb.predict(X_test)

print(f"Hoàn thành dự đoán cho {len(X_test)} mẫu!")

# Phân phối kết quả trên toàn bộ test set
unique_full, counts_full = np.unique(Y_pred_full_sklearn, return_counts=True)
print(f"\nPhân phối dự đoán trên toàn bộ test set ({len(X_test)} mẫu):")
for class_val, count in zip(unique_full, counts_full):
    print(f"Class {class_val}: {count:,} mẫu ({count/len(X_test)*100:.2f}%)")

# Tạo submission file
test_building_ids = test_values['building_id']
submission = pd.DataFrame({
    'building_id': test_building_ids,
    'damage_grade': Y_pred_full_sklearn
})

# Lưu file submission
submission.to_csv('submission_predictions.csv', index=False)
print(f"\nĐã lưu kết quả dự đoán vào file 'submission_predictions.csv'")
print(f"Submission file shape: {submission.shape}")
print("\nMẫu submission file:")
print(submission.head(10))

Dự đoán toàn bộ test set...
Hoàn thành dự đoán cho 86868 mẫu!

Phân phối dự đoán trên toàn bộ test set (86868 mẫu):
Class 1: 8,147 mẫu (9.38%)
Class 2: 77,445 mẫu (89.15%)
Class 3: 1,276 mẫu (1.47%)

Đã lưu kết quả dự đoán vào file 'submission_predictions.csv'
Submission file shape: (86868, 2)

Mẫu submission file:
   building_id  damage_grade
0       300051             2
1        99355             2
2       890251             2
3       745817             1
4       421793             2
5       871976             2
6       691228             1
7       896100             2
8       343471             2
9       766647             2

##### Tổng kết và Phân tích Kết quả

In [20]:
# Tổng kết và phân tích kết quả
print("="*60)
print("TỔNG KẾT KẾT QUẢ BERNOULLI NAIVE BAYES")
print("="*60)

print("\n1. DỮ LIỆU:")
print(f"   - Training samples: {len(X_train):,}")
print(f"   - Test samples: {len(X_test):,}")
print(f"   - Features sử dụng: {len(binary_features)} trường nhị phân")
print(f"   - Classes: {sorted(set(y_train))}")

print("\n2. PHÂN PHỐI CLASSES TRONG TRAINING:")
for i, label in enumerate(labels):
    class_name = int(label[0])
    prob = float(label[1])
    count = int(prob * len(y_train))
    damage_type = ["", "Thiệt hại nhẹ", "Thiệt hại trung bình", "Phá hủy hoàn toàn"][class_name]
    print(f"   Class {class_name} ({damage_type}): {count:,} mẫu ({prob*100:.2f}%)")

print("\n3. KẾT QUẢ DỰ ĐOÁN TRÊN TEST SET:")
for class_val, count in zip(unique_full, counts_full):
    damage_type = ["", "Thiệt hại nhẹ", "Thiệt hại trung bình", "Phá hủy hoàn toàn"][class_val]
    print(f"   Class {class_val} ({damage_type}): {count:,} mẫu ({count/len(X_test)*100:.2f}%)")

print("\n4. SO SÁNH IMPLEMENTATION:")
print(f"   - Hardcode implementation: Hoạt động chính xác")
print(f"   - Sklearn BernoulliNB: Hoạt động chính xác") 
print(f"   - Độ khớp giữa 2 methods: 100% (trên {test_size} mẫu test)")

print("\n5. CÁC TRƯỜNG DỮ LIỆU SỬ DỤNG:")
print("   Superstructure features (11 trường):")
superstructure_features = [f for f in binary_features if 'superstructure' in f]
for i, feature in enumerate(superstructure_features, 1):
    print(f"     {i:2d}. {feature}")

print("\n   Secondary use features (11 trường):")
secondary_features = [f for f in binary_features if 'secondary_use' in f]
for i, feature in enumerate(secondary_features, 1):
    print(f"     {i:2d}. {feature}")

print(f"\n6. OUTPUT FILES:")
print(f"   - submission_predictions.csv: {len(X_test):,} dự đoán cho test set")

============================================================
TỔNG KẾT KẾT QUẢ BERNOULLI NAIVE BAYES
============================================================

1. DỮ LIỆU:
   - Training samples: 260,601
   - Test samples: 86,868
   - Features sử dụng: 22 trường nhị phân
   - Classes: [1, 2, 3]

2. PHÂN PHỐI CLASSES TRONG TRAINING:
   Class 1 (Thiệt hại nhẹ): 25,124 mẫu (9.64%)
   Class 2 (Thiệt hại trung bình): 148,259 mẫu (56.89%)
   Class 3 (Phá hủy hoàn toàn): 87,218 mẫu (33.47%)

3. KẾT QUẢ DỰ ĐOÁN TRÊN TEST SET:
   Class 1 (Thiệt hại nhẹ): 8,147 mẫu (9.38%)
   Class 2 (Thiệt hại trung bình): 77,445 mẫu (89.15%)
   Class 3 (Phá hủy hoàn toàn): 1,276 mẫu (1.47%)

4. SO SÁNH IMPLEMENTATION:
   - Hardcode implementation: Hoạt động chính xác
   - Sklearn BernoulliNB: Hoạt động chính xác
   - Độ khớp giữa 2 methods: 100% (trên 100 mẫu test)

5. CÁC TRƯỜNG DỮ LIỆU SỬ DỤNG:
   Superstructure features (11 trường):
      1. has_superstructure_adobe_mud
      2. has_superstructure_mud_mortar_stone
      3. has_superstructure_stone_flag
      4. has_superstructure_cement_mortar_stone
      5. has_superstructure_mud_mortar_brick
      6. has_superstructure_cement_mortar_brick
      7. has_superstructure_timber
      8. has_superstructure_bamboo
      9. has_superstructure_rc_non_engineered
     10. has_superstructure_rc_engineered
     11. has_superstructure_other

   Secondary use features (11 trường):
      1. has_secondary_use
      2. has_secondary_use_agriculture
      3. has_secondary_use_hotel
      4. has_secondary_use_rental
      5. has_secondary_use_institution
      6. has_secondary_use_school
      7. has_secondary_use_industry
      8. has_secondary_use_health_post
      9. has_secondary_use_gov_office
     10. has_secondary_use_use_police
     11. has_secondary_use_other

6. OUTPUT FILES:
   - submission_predictions.csv: 86,868 dự đoán cho test set